language: android
before_script:
  - touch local.properties
android:
  components:
    - build-tools-26.0.2
    - android-26
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
install:
    - echo yes | sdkmanager "tools"
deploy:
  provider: script
  script: ./gradlew clean build bintrayUpload -PbintrayUser=jintin -PbintrayKey=$BINTRAY_KEY -PdryRun=false
  on:
    branch: master